SoporteRSL/SoporteRSL/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from .utils import redireccionar
from Investigadores.views import inicio
from Revisiones.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', redireccionar),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.auth_logout, name='logout'),
    path('inicio/', inicio, name='inicio'),
    #path('revisiones/nueva_revision', RevisionCreateView.as_view(), name='revision_add'),
    path('revisiones/comenzar_revision', comenzar_revision , name='comenzar-revision'),
    path('revisiones/nueva_revision', nueva_revision , name='nueva-revision'),
    path('revisiones/<int:revision_id>/', detalle, name='detalle'),
    path('crear_formulario/<int:revision_id>/', crear_formulario, name='crear-formulario'),
    path('ayuda/', ayuda, name='ayuda'),
    path('ayuda/actividad_1',actividad_1, name='actividad-1'),
    path('ayuda/actividad_2',actividad_2, name='actividad-2'),
    path('ayuda/actividad_3',actividad_3, name='actividad-3'),
]

SoporteRSL/Revisiones/models.py
from django.db import models
from Investigadores.models import Investigador

# Create your models here.

class PreguntaDeInvestigacion(models.Model):
    pregunta = models.CharField(max_length=150)
    revision = models.ForeignKey('Revision', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural="preguntas de investigacion" 

    def __str__(self):
        return '%s -- %s' % (self.pregunta,self.revision) 

class Metadato(models.Model):
    nombre = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural="metadatos"

    def __str__(self):
        return '%s' % (self.nombre) 


class Biblioteca(models.Model):
    nombre = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural="bibliotecas"

    def __str__(self):
        return '%s' % (self.nombre)


class Criterio(models.Model):

    TIPO_DE_CRITERIO_CHOICE=(
        ('IN', 'inclusion'),
        ('EX', 'exclusion'),
        ('CA', 'calidad')
    )

    tipo = models.CharField(max_length=2, choices=TIPO_DE_CRITERIO_CHOICE, default='inclusion')
    descripcion = models.CharField(max_length=200)
    revision = models.ForeignKey("Revision", on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural="Criterios"

    def __str__(self):
        return '%s - %s' % (self.tipo, self.descripcion)


class Articulo(models.Model):
    titulo = models.CharField(max_length= 50)
    revision = models.ForeignKey("Revision", on_delete=models.CASCADE)
    leido = models.BooleanField(default=False , verbose_name="¿El articulo fue leeido?" )
    archivo = models.FileField(upload_to="articulos/")
    formulario_de_extraccion = models.FileField(upload_to="formularios_de_extraccion/")

    class Meta:
        verbose_name_plural = "Articulos"

    def __str__(self):
        return '%s' % (self.titulo)

class Modificacion(models.Model):
    revision = models.ForeignKey("Revision", on_delete=models.CASCADE)
    investigador = models.ForeignKey('Investigadores.Investigador', on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    descripcion = models.CharField(max_length=150)

    class Meta:
        verbose_name_plural = "Modificaciones"

    def __str__(self):
        return 'Modificacion - %s - revision - %s' % (self.fecha,self.revision)

class Revision(models.Model):
    ESTADO_CHOICE=(
        ('A1', 'Actividad 1'),
        ('A2', 'Actividad 2'),
        ('A3', 'Actividad 3')
    )

    titulo = models.CharField(max_length=80)
    meta_de_necesidad_de_informacion = models.CharField(max_length=500)
    investigadores = models.ManyToManyField('Investigadores.Investigador', verbose_name= "Investigadores")
    cadena_de_busqueda = models.CharField(max_length=200,)
    metadatos = models.ManyToManyField("Metadato")
    bibliotecas = models.ManyToManyField("Biblioteca")
    prueba_piloto = models.BooleanField(default=False, verbose_name= "¿Se realizara prueba piloto?")
    estado = models.CharField(max_length=2, choices=ESTADO_CHOICE, default='Actividad 1')
    fecha_inicio = models.DateField(auto_now_add=True)
    formulario_generico = models.BooleanField(default=False, verbose_name= "¿Se creo un formulario de extraccion de datos?")
    class Meta:
        verbose_name_plural="revisiones"

    def __str__(self):
        return '%s' % (self.titulo)

SoporteRSL/Revisiones/forms.py
from django import forms
from .models import Revision, PreguntaDeInvestigacion, Criterio, Articulo
from Investigadores.models import Investigador
from django.forms import modelformset_factory

class RevisionFormInicial(forms.ModelForm):
    class Meta:
        model = Revision
        fields = ['titulo','meta_de_necesidad_de_informacion','investigadores']


class RevisionForm(forms.ModelForm):
    class Meta:
        model = Revision
        fields = ['cadena_de_busqueda','metadatos','bibliotecas','prueba_piloto']



class PreguntaDeInvestigacionForm(forms.ModelForm):

    class Meta:
        model = PreguntaDeInvestigacion
        fields = ['pregunta']


class CriterioForm(forms.ModelForm):
    class Meta:
        model = Criterio
        fields = ['tipo','descripcion']


class ArticuloForm(forms.ModelForm):
    
    class Meta:
        model = Articulo
        fields = ['titulo','archivo','leido']


class MetadatosForm(forms.ModelForm):
    class Meta:
        model = Revision
        fields = ['metadatos']

SoporteRSL/Revisiones/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView
from django.http import Http404, HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404

from docx import Document
from docx.shared import Inches
import os

from .models import *
from .forms import RevisionForm, MetadatosForm, RevisionFormInicial

@login_required
def nueva_revision(request):

    if request.method == 'POST':
        revision_form = RevisionForm(request.POST)

        print(request.POST)
        if revision_form.is_valid():

            investigador = Investigador.objects.get(usuario__username = request.user)
            revision = get_object_or_404(Revision, pk=request.POST.get('id_revison',0))

            PreguntaDeInvestigacion.objects.filter(revision__pk =request.POST.get('id_revison',0)).delete()

            for x in range((int(request.POST['preguntas-TOTAL_FORMS']))):
                if request.POST.get('pregunta-'+str(x),False) != "BORRAR" and request.POST.get('pregunta-'+str(x),False) != "":
                    pregunta = PreguntaDeInvestigacion()
                    pregunta.revision = revision
                    pregunta.pregunta = request.POST.get('pregunta-'+str(x),False)
                    pregunta.save()

            revision.metadatos.clear()
            lista_metadatos = request.POST.getlist('metadatos')             
            for metadato in lista_metadatos:
                revision.metadatos.add(Metadato.objects.get(pk=metadato))
            
            lista_bibliotecas = request.POST.getlist('bibliotecas')
            revision.bibliotecas.clear()
            for biblioteca in lista_bibliotecas:
                revision.bibliotecas.add(Biblioteca.objects.get(pk=biblioteca))
            
            revision.cadena_de_busqueda = request.POST['cadena_de_busqueda']

            Criterio.objects.filter(revision__pk =request.POST.get('id_revison',0)).delete()

            for x in range(1,(int(request.POST['criterios-TOTAL_FORMS']))):
                if request.POST.get('id_criterio-'+str(x)+'-descripcion') != "BORRAR":
                    criterio = Criterio()
                    criterio.descripcion = request.POST.get('id_criterio-'+str(x)+'-descripcion')
                    criterio.tipo = request.POST.get('id_criterio-'+str(x)+'-tipo')
                    criterio.revision = revision
                    criterio.save()

            revision.save()

            modificacion = Modificacion()
            modificacion.revision = revision
            modificacion.investigador = investigador
            modificacion.descripcion = "Nueva informacion de actividad 1 añadida"
            modificacion.save()

            return HttpResponseRedirect('/inicio/')
        else:
            return HttpResponseRedirect('/inicio/')
    else:        
        print(request)
        revisiones = Revision.objects.filter(investigadores__usuario__pk = request.user.pk)
        return render(request, 'revisiones/nueva_revision.html', {
            'revisiones':revisiones,
            'revision_form': revision_form,
        })

@login_required                
def comenzar_revision(request):

    if request.method == 'POST':
        
        print(request.POST)
        
        revision = Revision()
        investigador = Investigador.objects.get(usuario__username = request.user)

        revision.meta_de_necesidad_de_informacion = request.POST['meta_de_necesidad_de_informacion']
        revision.titulo = request.POST['titulo']
        revision.save()

        for i in request.POST['investigadores']:
            revision.investigadores.add(Investigador.objects.get(pk=i))

        modificacion = Modificacion()
        modificacion.revision = revision
        modificacion.investigador = investigador
        modificacion.descripcion = "Creación"
        modificacion.save()

        return HttpResponseRedirect('/inicio/')
    else:
        revision_form = RevisionFormInicial()

    revisiones = Revision.objects.filter(investigadores__usuario__pk = request.user.pk)
    context = {
        'revisiones':revisiones,
        'revision_form': revision_form,
    }
    
    
    return render(request, 'revisiones/comenzar_revision.html', context)


@method_decorator(login_required, name='dispatch')
class RevisionCreateView(CreateView):
    model = Revision
    fields = ['titulo',
    'meta_de_necesidad_de_informacion',
    'investigadores',
    'cadena_de_busqueda',
    'metadatos',
    'bibliotecas',
    'prueba_piloto']
    success_url = "../inicio/"

    
@login_required
def detalle(request, revision_id):
    try:
        revisiones = Revision.objects.filter(investigadores__usuario__pk = request.user.pk)
        revision = Revision.objects.get(pk=revision_id)
        revision_form = RevisionForm(instance=revision)
        
        investigadores = Investigador.objects.filter(revision__pk = revision_id)
        preguntas = PreguntaDeInvestigacion.objects.filter(revision__pk = revision_id)
        criterios = Criterio.objects.filter(revision__pk = revision_id)
        articulos = Articulo.objects.filter(revision__pk = revision_id)
        context = {
            'revisiones':revisiones,
            'revision': revision,
            'investigadores': investigadores,
            'articulos': articulos,
            'preguntas': preguntas,
            'criterios': criterios,
            'revision_form': revision_form,
        }
    
    
    except Revision.DoesNotExist:
        raise Http404("La revision no existe")

    if revision.estado == 'Actividad 1':
        
        return render(request, 'revisiones/nueva_revision.html', context)
    else:
        return render(request, 'revisiones/detalle.html', context)

@csrf_exempt
def crear_formulario(request, revision_id):

    document = Document('media/Template of the Data Extraction Form.docx')
    
    revision = Revision.objects.get(pk=revision_id)
    
    table = document.add_table(rows=0, cols=2)
    table.style = 'estilo template'

    for i in range(1,(int(request.POST.get('cant-campos',0))+1)):
        if (request.POST.get('campo-'+str(i), 'campo no existente') != "BORRAR"):
            row = table.add_row()
            row.cells[0].text = request.POST.get('campo-'+str(i), 'campo no existente')
            

    if not os.path.exists('media/'+str(revision_id)):
        os.makedirs('media/'+str(revision_id))
    
    documento_creado = True

    document.save('media/'+str(revision_id)+'/Formulario de extraccion.docx')
    revision.formulario_generico = True
    revision.save()
    #return HttpResponseRedirect('/revisiones/'+ str(revision_id))
    return JsonResponse({'documento_creado': documento_creado})

def ayuda(request):
    revisiones = Revision.objects.filter(investigadores__usuario__pk = request.user.pk)
    context = {
            'revisiones':revisiones,
        }

    return render(request, 'SoporteRSL/ayuda.html', context)

def actividad_1(request):

    revisiones = Revision.objects.filter(investigadores__usuario__pk = request.user.pk)
    context = {
            'revisiones':revisiones,
        }

    return render(request, 'SoporteRSL/actividades/actividad_1.html', context)

def actividad_2(request):
    
    revisiones = Revision.objects.filter(investigadores__usuario__pk = request.user.pk)
    context = {
            'revisiones':revisiones,
        }

    return render(request, 'SoporteRSL/actividades/actividad_2.html', context)

def actividad_3(request):
    
    revisiones = Revision.objects.filter(investigadores__usuario__pk = request.user.pk)
    context = {
            'revisiones':revisiones,
        }

    return render(request, 'SoporteRSL/actividades/actividad_3.html', context)

SoporteRSL/templates/Revisiones/Revision_form.htm
{% extends '../base.html' %}
{% load static %}


{% block content %} 
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

SoporteRSL/templates/Revisiones/comenzar_revision.html
{% extends '../base.html' %} {% load static %} {% block content %}

<div class="w3-container">
  <h2>Comenzar una nuevo proyecto de revision</h2>
  <form action="/revisiones/comenzar_revision" method="post">
    {% csrf_token %}

    <div id="MetaInformacion" class="w3-container city">
      <p>
        <label for="id_titulo">Titulo de la revision:</label>
        {{ revision_form.titulo }}
      </p>
      <p>
        <label for="id_meta_de_necesidad_de_informacion"
          >Meta de necesidad de informacion:</label
        >
        {{ revision_form.meta_de_necesidad_de_informacion }}
      </p>
      <p>
        <label for="id_investigadores">Investigadores participantes:</label>
        {{ revision_form.investigadores }}
      </p>
    </div>
    <input class="w3-hover-green w3-margin-top" type="submit" value="Guardar" />
  </form>
</div>

<script src="{% static 'revisiones/js/nueva_revision.js' %}"></script>
{% endblock %}

SoporteRSL/templates/Revisiones/detalle.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
<div class="w3-container w3-card cuerpo">
  <h1 class="w3-center w3-theme-l4 titulo">{{ revision.titulo }}</h1>

  <article class="w3-container">

    <p><b>Meta: </b> {{ revision.meta_de_necesidad_de_informacion }}</p>
    <p><b>Fecha incial: </b> {{ revision.fecha_inicio }}</p>
    <p><b>Estado actual de la revision: </b> {{ revision.estado }}</p>

  </article>
</div>
<section class="w3-panel w3-card cuerpo">
  <h3 class="w3-center w3-theme-l4 titulo">Preguntas de Investigacion</h3>
  <div class="w3-container w3-margin-bottom">
    <ul class="w3-ul w3-margin-bottom">
      {% for pregunta in preguntas %}
      <li>{{ pregunta.pregunta }}</li>
      {% endfor %}
    </ul>
  </div>
</section>

<section class="w3-panel  w3-card cuerpo">
  <h3 class="w3-center w3-theme-l4 titulo">Protocolo de busqueda</h3>
  <div class="w3-row w3-margin-bottom">
    <div class="w3-container w3-third w3-mobile">
      <h4>Cadena de Busqueda</h4>
      <p>{{ revision.cadena_de_busqueda }}</p>
    </div>
    <div class="w3-container w3-third w3-mobile">
      <div class="w3-row">
        <div class= 'w3-col' style="width:80%">
            <h4>Metadatos</h4>
        </div>
        <div class="w3-col"  style="width:20%">
            <a class="w3-button w3-large w3-circle w3-theme-action">+</a>
        </div>
      </div>
      
      
      <ul class="w3-ul ">
        {% for metadato in metadatos %}
        <li>{{ metadato }}</li>
        {% endfor %}
      </ul>
    </div>
    <div class="w3-container w3-third w3-mobile">
      <h4>Bibliotecas Utilizadas</h4>
      <ul class="w3-ul ">
        {% for biblioteca in bibliotecas %}
        <li>{{ biblioteca.nombre }}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
</section>


<section class="w3-panel w3-card w3-margin-bottom cuerpo">
  <h3 class="w3-center w3-theme-l4 titulo">Investigadores</h3>
  <div class="w3-container w3-margin-bottom">
    <ul class="w3-ul ">
      {% for investigador in investigadores %}
      <li class="w3-bar w3-border">
        <div class="w3-bar-item">
          <span class="w3-large">{{ investigador }}</span><br>
          <span>Rol: </span>
        </div>
      </li>
      {% endfor %}
    </ul>





  </div>
</section>

<section class="w3-panel w3-card cuerpo">
  <h3 class="w3-center w3-theme-l4 titulo">Articulos</h3>
  <div class="w3-container w3-margin-bottom">
    <table class="w3-table w3-border w3-striped">
      <tr>
        <th></th>
        <th>Titulo</th>
        <th>Leido?</th>
        <th>Formulario de extraccion</th>
      </tr>

      {% for articulo in articulos %}
      <td>x</td>
      <td>{{ articulo.titulo }}
      <td>{{ articulo.leido }}</td>
      <td></td>
      {% endfor %}

    </table>
    <!--<form action="/file-upload" class="dropzone w3-padding-64 w3-theme-l4">
      <div class="fallback">
        <input name="file" type="file" multiple />
      </div>
             
  </div>
  </form> -->
  </div>
  <section class="w3-panel">
    <!--<Button action="" class="w3-button w3-block w3-black">Generar formulario de extraccion de datos</button>-->
    <a class="w3-button w3-block w3-black" href="{% url 'crear-formulario' revision.pk %}">Generar formulario de
      extraccion de datos</a>
  </section>
</section>



<script>
$(document).ready(function () {

    if ("{{ revision.estado }}" === "Actividad 1") {
     
     // $(".titulo").removeClass('w3-theme-l4');
     // $(".titulo").addClass('w3-light-blue');
      
    }

});

</script>
{% endblock %}

SoporteRSL/templates/Revisiones/revision_form.html
{% extends '../base.html' %}
{% load static %}


{% block content %} 

<h1>Crea una nueva revision</h1>
<form method="post" id= "formulario">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="w3-button w3-black w3-hover-green" type="submit" value="Guardar">
</form>

<div class="w3-container">
  <h2>Tabs in a Grid</h2>

  <div class="w3-row">
    <a href="javascript:void(0)" onclick="ControladorTab(event, 'London');">
      <div class="w3-third tablink w3-bottombar w3-hover-light-grey w3-padding">London</div>
    </a>
    <a href="javascript:void(0)" onclick="ControladorTab(event, 'Paris');">
      <div class="w3-third tablink w3-bottombar w3-hover-light-grey w3-padding">Paris</div>
    </a>
    <a href="javascript:void(0)" onclick="ControladorTab(event, 'Tokyo');">
      <div class="w3-third tablink w3-bottombar w3-hover-light-grey w3-padding">Tokyo</div>
    </a>
  </div>

  <div id="London" class="w3-container city" style="display:none">
    <h2>London</h2>
    <p>London is the capital city of England.</p>
  </div>

  <div id="Paris" class="w3-container city" style="display:none">
    <h2>Paris</h2>
    <p>Paris is the capital of France.</p> 
  </div>

  <div id="Tokyo" class="w3-container city" style="display:none">
    <h2>Tokyo</h2>
    <p>Tokyo is the capital of Japan.</p>
  </div>
</div>



{% endblock %}